#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
REPLICATION HEADER
  PRODUCES   02_output/values/values_generated.tex, VALUES_DIFF.md,
             02_output/tables/disagreements.tex and 02_output/tables/eps_dyn.tex
  FEEDS      manuscript/values.tex, tab:disagreements, tab:eps_dyn
  INPUTS     computed.json, inputs_literature.py (the previous manuscript/values.tex, if any,
             is read for VALUES_DIFF.md only)
  SEED       none
  RUNTIME    about 4 s
  IMPLEMENTS no equation; the value-generation stage

make_tables_values.py — STAGE A generator (safe, diffable, NON-destructive).

Reads the sourced literature inputs (inputs_literature.py) and the regenerated computed
outputs (02_output/computed.json, produced by collect_computed.py) and writes:

  02_output/values/values_generated.tex   candidate values.tex (every macro defined),
                                           in TWO labelled blocks:
                                             (1) Literature inputs  (sourced constants)
                                             (2) Computed outputs   (regenerated by code)
  02_output/tables/disagreements.tex       tab:disagreements (cells are macros of values.tex)
  02_output/tables/eps_dyn.tex             tab:eps_dyn (cells are macros of values.tex)
  02_output/values/VALUES_DIFF.md          per-macro diff: paper vs generated, classified

Anti-fabrication: a computed value comes only from computed.json (a real run). A literature
value comes only from inputs_literature.py (sourced). A macro that is NEITHER stops the run
and is named on the way out. There is no third path. The list of macros
itself comes from the generators (computed.json keys and inputs_literature.py, minus
REMOVED_MACROS), and every value is written as its generator formatted it: the previous
values.tex can be deleted before a run without changing a byte of the output.

Why there is no third path, and specifically no fallback that copies the manuscript's own
value: manuscript/values.tex is not an independent record of anything. Step 3/5 of
run_all.sh overwrites it with the file this script writes, so a value taken from it would
be read out of the previous run's output and written straight back into the next one, and
would agree with itself for as long as nobody looked. A fallback that quietly preserves a
number is not the conservative option; it is the one failure a reproduction check cannot
detect. Hence: named, and fatal.

NOTHING here overwrites the manuscript (Stage A).

Usage:  python make_tables_values.py        (uses existing computed.json)
        python make_tables_values.py --collect   (re-run collect_computed.py first)
"""
import re, sys, json, subprocess, argparse
from pathlib import Path

HERE = Path(__file__).resolve().parent
CODE = HERE.parent
ROOT = CODE.parent
MANU_VALUES = ROOT / "manuscript" / "values.tex"
VALDIR = ROOT / "02_output" / "values"
TABDIR = ROOT / "02_output" / "tables"
COMPUTED = ROOT / "02_output" / "computed.json"
sys.path.insert(0, str(CODE))
from inputs_literature import LITERATURE_MACROS  # noqa: E402

# Macros with zero references in paper.tex and all tables
# (see 02_output/UNUSED_MACRO_CHECK.md). They are dropped from the generated values.tex.
# NOT included: the 9 "unused-in-current-paper" macros still referenced in paper_past.tex.
REMOVED_MACROS = {
    # The published-cascade appendix no longer quotes the elasticity of the ceiling in
    # warming (the sign change at nu*, the elasticity at nu = 1, the premium integrated to
    # T_upper). bhp_bound.py still computes the three numbers and keeps its assertion on
    # bhpNuStar (computed.json keeps them); bhpTupper stays in inputs_literature.py:
    "bhpNuStar", "bhpElasticityNuOne", "bhpPremiumRatio", "bhpTupper",
    # Ssec:which_parameter no longer quotes the class factor at the central AMOC
    # threshold, only at the near end of the range and at eps_dyn. collect_computed.py still
    # computes it (computed.json keeps it):
    "xoverClassFactorAtCentral",
    # The loose bound on the moving-budget error (old D.2, eq. 31) left
    # the paper; the draining-budget appendix quotes the direct computation only. collect_computed.py still computes
    # both and keeps its assertions (computed.json keeps them):
    "additivityErrAMOC", "additivityErrAmazon",
    # Uncalled by paper.tex, tables/*.tex and every figure script's
    # FIGURE_MACROS. Their generators still compute them (computed.json keeps them).
    # An earlier purge counted only paper.tex and the tables, and so dropped
    # nine numbers that fig:forest_tc prints or draws (the Amazon and ice-sheet SSP P10s, P90s and
    # not-reached shares). They are back; the rule now also counts FIGURE_MACROS, and
    # main() refuses any entry here that a figure declares. The AMOC is not on fig:forest_tc,
    # so its three SSP numbers stay out:
    "tcAMOCSSPhighNotReachedPct", "tcAMOCSSPhighPten", "tcAMOCSSPmidPten",
    # The TCRE is no longer clipped to [0.14, 0.82]; the only
    # constraint is TCRE > 0, by rejection (tcre_draw.py), so the truncation has no macro.
    "TCRElo", "TCREhi", "TCREloGtC", "TCREhiGtC",
    # Numerical-methods appendix rewritten: the transcritical sentence quotes \valTcFoldGapPct (the mu = 0
    # constant against L Phi_fold/sigma^(2/3)); the price-against-constant gap is not quoted.
    "valTcLimitDevPct",
    # At fixed state the pitchfork's slope tends to +1/2, not -1/2, and the
    # transcritical's price to zero, not to the constant; the numerical-methods appendix quotes \valPitchSlopeFix and
    # \valTcSlopeFix instead.
    "valPitchSlopeFar", "valTcFoldGapPct",
    # The coupled-elements appendix rewritten without numbers; coupled_folds.py removed (its closed form
    # used the abandoned Airy amplitude).
    "coupledBetaBound", "coupledSlopeEff", "coupledSlopeNaive",
    # The appendix on where the elements sit quotes the shortfall of the lift as a positive percentage
    # (\valSensFShortPct*); the signed gaps stay in computed.json.
    "valSensFGapPctLo", "valSensFGapPctHi",
    # not reached before 2500 is no longer written; the text says why (zero by 2250):
    "emissionPathLastYear",
    # note 4 now quotes the ice sheet against the Amazon only (\fracWAISbeforeAmazon*):
    "fracWAISfirst", "fracWAISfirstIncl",
    # the ordering paragraph of ssec:comparable quotes the realization factor of the two dated elements:
    "OmegaAMOCmed",
    # the bound at central inputs; the bound appendix quotes \recNPtcNow instead:
    "tcAMOCcentral",
    # ssec:comparable no longer names backstop scenarios (the bound does not depend on the cost):
    "gammabarLow", "gammabarHigh",
    # literature inputs with no caller since Howard and Sterner left the body:
    "dmgSCCRatioLo", "dmgSCCRatioHi",
    # Renamed, not retired. The recovery rate is theta in the paper,
    # lambda being kept for the arrival rate; the same values are emitted under the new names
    # (thetaAMOChat, recThetaW*, recJointThetaDecline, sigmaAggregationFactorTheta).
    "lambdaAMOChat", "recLambdaWFloor", "recLambdaWMinValid", "recLambdaWFail",
    "recLambdaWPass", "recJointLamDecline", "sigmaAggregationFactorLambda",
    # No call left in paper.tex or tables/*.tex once the appendices on
    # the discount rate and on the signature that separates the classes (with
    # fig_cross_partial) left the paper. Their scripts, where they still run, still compute them.
    "phiRatioDiscountRange", "priceRatioDiscountAMOC", "priceRatioDiscountAmazon",
    "priceRatioDiscountWAIS", "rhoRangeHiPct", "rhoRangeLoPct",
    "crosspartialAsymptote", "crosspartialBpct", "etaFlipExponent", "etaFlipMarginRatio",
    "etaFlipPrefac", "sigmaPairHigh", "sigmaPairLow",
    # No \ call left in paper.tex or tables/*.tex after the body was
    # rebuilt and the appendices cut. Their scripts still compute them;
    # listing them here keeps them out of values.tex, as for every retired macro below.
    # The vdB-H-vdP kink paragraph and the cascade unravelling time left the paper:
    "bhpEzero", "bhpFzero", "bhpKinkE", "bhpKinkYears", "bhpUnravel", "bhpElasticityNuZero",
    # eps_dyn of the AMOC is no longer quoted; the window is stated without it.
    # (\epsDynAMOC is quoted again, in ssec:which_parameter, fig:crossover and tab:eps_dyn, and left
    # this list; the band fraction stays out.)
    "bandFractionPct",
    # The reduced-form breakeven and validity numbers, and the anchor exponent:
    "dphysBreakevenIAM", "dphysBreakevenSdRatio", "dphysSdRatioLambda", "dphysValidityMax",
    "reducedExponentAnchor",
    # Additivity threshold and the plotted-pair bounds of the old signature subsection:
    "epsAdditivity", "epsPairValidityMax", "epsPlotMax", "etaStarAtPlotMax",
    # The reversal frontier at the AMOC point and its logarithmic law; the contrast ratios:
    # (\etaStarReversal, once retired here, was later called again from the appendix.)
    "etaFlipAMOC", "etaStarBreakeven", "reversalLawSlope",
    "ratioContrastFar", "ratioContrastNear",
    # Ordering shares the text no longer quotes; record length; the amplitude slope at zero:
    "fracAmazonBeforeAMOC", "jointSamplePct", "HadISSTyears", "PhiPrimeZero",
    # Added once and not called in the end (the 80% record length); its line
    # was removed from record_detectability.py as well.
    "recTrendLengthEighty",
    # The floor's shortening of the bound needs the amplitude A, which
    # fig_forest_tc.py evaluates with sigma in the observable's units against M* in
    # gigatonnes, i.e. with the physical margin d_phys implicitly set to one -- the number
    # ssec:window declares unmeasured. An artefact of that pairing, not a result.
    "floorShorteningMax",
    "MstarSPGmed", "TSPG", "crosspartialFoldEpsTwenty", "epsSPGnat", "fSPGmed",
    "sccAMOCCIhigh", "sccAMOCCIlow", "sccAMOCnaturalProx", "sccAMOCrecon",
    "sccAmazonrecon", "sccSPGrecon", "sccTotalRecon", "sccWAISrecon", "sigmaWAISmed",
    # Withdrawn with Table 2: these carried the dimensionally inconsistent SCC LEVEL
    # (see the note in collect_computed.py). Their generator no longer emits them; they
    # are listed here so a stale computed.json cannot reintroduce them either.
    "sccPerElemLow", "sccPerElemHigh", "sccTotalRangeLow", "sccTotalRangeHigh",
    "sccWAISraw", "sccWAISafterF",
    # Retired with the move of the cross-partial contrasts onto the pair of noise levels
    # the archived cross-partial figure plotted. \sigmaContrastRef named the single sigma the old
    # local derivative was quoted at; \absGap* carried the absolute gap between the two
    # classes, which is not a measure of detectability and is not monotone on the pair;
    # \etaFlipCommon was one constant where the sign change obeys a law in rho_tilde.
    "sigmaContrastRef", "absGapNear", "absGapFar", "etaFlipCommon",
    # Replaced by macros quoted in the units the surrounding text uses, so that the text
    # can call them instead of restating them in words: \dphysSdRatioIAM (SD per margin,
    # the inverse of what the sentence says) by \dphysBreakevenSdRatio, and
    # \etaStarAMOConeK (eta* at one kelvin) by \dphysValidityMax (the margin at eta* = 1).
    "dphysSdRatioIAM", "etaStarAMOConeK",
    # Went with the 481-line dormant draft that was their only remaining caller, and
    # with the withdrawal of the floor-based date in favour of the bound eq:tc_bound.
    "dphysBreakevenPub", "dphysSdRatioPub", "reducedExponentAMOC", "fracWAISimmediate",
    # Phase 4.2 sweep against the canonical manuscript. The IAM
    # comparison was recast as a breakeven margin, so it cites Dietz and Cai without
    # reproducing their figures, and these reported levels lost their only callers.
    "sccDietzBaseline", "sccDietzCentral", "sccDietzPct", "sccDietzScenHigh",
    "sccDietzScenLow", "sccDietzTotalHigh", "sccDietzTotalLow", "sccCaiLow", "sccCaiHigh",
    # Backstop scenarios the text no longer names: it contrasts \gammabarLow with \gammabarHigh
    # only, so the midpoint and the duplicate range bounds are unused.
    "cbarMid", "cbarRangeLow", "cbarRangeHigh",
    # The per-tonne abatement cost is written gamma(z) and the backstop cost
    # \bar\gamma, so the two scenarios the text names were renamed gammabarLow/High (same values).
    "cbarLow", "cbarHigh",
    # SPG was removed from the body (three elements remain), and \sigmaPriorPct named a
    # prior width the sigma subsection now states in its own words.
    "DTstarSPG", "sigmaPriorPct",
    # The forest reports \fracWAISfirst and \fracAmazonBeforeAMOC, not the full order,
    # since the calibration does not resolve the order of the two behind the ice sheet.
    "fracFullOrder",
    # Retired with the rewrite of the fourth limit. \etaStarNow read eta* at the deduced
    # margin d_phys = lambda, a convention in years that the persistence bound excludes
    # physically, and \etaStarReversalRatio was eta*_rev divided by it, so it carried the
    # same convention. Neither has a caller left. Listed here so a stale
    # computed.json cannot reinstate them.
    "etaStarNow", "etaStarReversalRatio",
    # Renamed, not retired: \tauWindowThresholdAmazon. The transport that carries the
    # persistence bound to the present runs at the ELEMENT'S OWN proximity, so the
    # relaxation time below which an element leaves the validity window is element-specific.
    # \tauWindowThreshold was computed at the AMOC's eps_0 and quoted in a sentence about
    # the Amazon. It is listed here so a stale computed.json cannot keep the old number
    # alive after the generator stopped emitting it: with no definition, paper.tex fails
    # loudly at the one call site instead of compiling a stale 41.
    "tauWindowThreshold",
    # Went with paper3_persistence_bound.py. ssec:scope_persistence keeps the argument in
    # WORDS and quotes none of these eleven, so the package was computing eleven values the
    # manuscript does not read. Their one downstream consumer is archived too. Listed here so
    # a stale computed.json cannot bring any
    # of them back after the generator has gone.
    "persistRelaxTimes",
    "persistRelaxTimesRev",
    "etaStarPersistAMOC",
    "etaStarPersistHolocene",
    "dphysPersistenceSd",
    "dphysPersistenceHolocene",
    "persistHoloceneRatio",
    "tauAMOC",
    "tauWindowThresholdAmazon",
    "rhoTildeAMOC",
    "persistPrefactorSlack",
    # Went with paper3_skewness_margin.py when the asymmetry argument left the manuscript
    # (zero occurrences of "skew" in paper.tex). The script was the package's only reader of
    # the three NOAA PSL series, which are archived with it, and its own independent fetch of
    # the PIK series was the package's second network call. Listed here so a stale
    # computed.json cannot reintroduce the macro after its generator has gone.
    "skewYearsRequired",
    # Went with crosspartial_mstar.py in the 2026-09 cleanup. It named the z at which the
    # quadratic term of the class-B price correction overtakes the linear one, and the
    # passage that used it was cut from the paper. Nothing else came out of that script,
    # so the macro and its only generator left together.
    "etaCubicCrossover",
    # NOT removed although currently uncalled: \EglobalRate (40 GtCO2/yr). It is E_0,
    # which sets the deadline bound eq:tc_bound, and the paper states that bound
    # symbolically without ever giving E_0 a value. Dropping the macro would bury the gap,
    # so it stays defined and uncited, and section 4 of README.md reports it as an orphan.
}


FIGDIR = CODE / "03_figures"
MANU = ROOT / "manuscript"


def figure_macros():
    """{macro: [figure scripts]} from the FIGURE_MACROS tuple each figure script declares.
    Read as text, so the scripts are not run. A figure script without the tuple is a hard
    failure: the purge rule cannot know what it prints."""
    out = {}
    for p in sorted(FIGDIR.glob("fig_*.py")):
        s = p.read_text(encoding="utf-8")
        m = re.search(r"^FIGURE_MACROS\s*=\s*\((.*?)\)", s, re.MULTILINE | re.DOTALL)
        if not m:
            raise SystemExit(f"[ERROR] {p.name} declares no FIGURE_MACROS tuple")
        for name in re.findall(r'"([A-Za-z]+)"', m.group(1)):
            out.setdefault(name, []).append(p.name)
    return out


def macros_in_use():
    """The purge rule: a macro is used if paper.tex, a tables/*.tex file or a
    figure script's FIGURE_MACROS names it. LaTeX comments do not count."""
    if not MANU.is_dir():
        raise SystemExit("[ERROR] --list-unused reads manuscript/paper.tex, and manuscript/ is not "
                         "present.")
    used = set(figure_macros())
    for f in [MANU / "paper.tex"] + sorted((MANU / "tables").glob("*.tex")):
        txt = "\n".join(re.sub(r"(?<!\\)%.*$", "", l)
                        for l in f.read_text(encoding="utf-8").split("\n"))
        used |= set(re.findall(r"\\([A-Za-z]+)", txt))
    return used


def previous_values():
    """{name: value} of the manuscript values.tex as it stands BEFORE this run, or {} if it
    does not exist. This is read for VALUES_DIFF.md only, a report. Neither the
    list of macros nor any value or precision written to values_generated.tex comes from it,
    so the file can be deleted before a run and the run writes the same bytes.
    Without manuscript/ (the public package), the previous file is the committed
    02_output/values/values_generated.tex, which the manuscript's copy equals byte for byte;
    it is read here, before this run overwrites it."""
    if not MANU.is_dir():
        if not (VALDIR / "values_generated.tex").exists():
            return {}
        return dict(re.findall(r"\\newcommand\{\\(\w+)\}\{((?:[^{}]|\{[^{}]*\})*)\}",
                               (VALDIR / "values_generated.tex").read_text(encoding="utf-8")))
    if not MANU_VALUES.exists():
        return {}
    # A value may carry ONE level of braces (a unit such as {}^{\circ}\mathrm{C}^{-1}).
    return dict(re.findall(r"\\newcommand\{\\(\w+)\}\{((?:[^{}]|\{[^{}]*\})*)\}",
                           MANU_VALUES.read_text(encoding="utf-8")))


def compare(prev_val, gen_val):
    """Verdict for VALUES_DIFF.md. Compares and reports; it changes nothing. (Until step
    29 bis this was match_precision, which REFORMATTED the generated value to the previous
    file's precision: the previous run's output was then an input of this one.)"""
    if prev_val is None:
        return "NEW (not in the previous values.tex)"
    pv = prev_val.replace("\\%", "").replace("%", "")
    gv = gen_val.replace("\\%", "").replace("%", "")
    if pv == gv:
        return "MATCH"
    try:
        d = float(gv) - float(pv)
    except ValueError:
        return "diff:check"
    rel = abs(d) / abs(float(pv)) if float(pv) else 1
    if d == 0:
        return "diff:format (same number, other digits)"
    if abs(d) <= 0.5 or rel <= 0.01:
        return f"diff:benign (Δ={d:+g})"
    return f"diff:SUBSTANTIVE (Δ={d:+g})"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--collect", action="store_true", help="re-run collect_computed.py first")
    ap.add_argument("--list-unused", action="store_true",
                    help="list the macros this run emits that the purge rule finds unused "
                         "(paper.tex, tables/*.tex, FIGURE_MACROS), and exit")
    args = ap.parse_args()

    # The purge rule, enforced: no figure may lose a number it prints or draws.
    fig = figure_macros()
    clash = sorted(set(fig) & REMOVED_MACROS)
    if clash:
        print("ERROR: REMOVED_MACROS drops macros that a figure prints or draws:")
        for name in clash:
            print(f"         \\{name}  ({', '.join(fig[name])})")
        return 1
    if args.collect or not COMPUTED.exists():
        subprocess.run([sys.executable, str(HERE / "collect_computed.py")], check=True)

    computed = json.loads(COMPUTED.read_text(encoding="utf-8"))
    # THE LIST OF MACROS COMES FROM THE GENERATORS ONLY: the keys of
    # computed.json and the sourced constants of inputs_literature.py, minus REMOVED_MACROS.
    # Until then it was read from manuscript/values.tex, so a run from an empty directory
    # failed on the missing file, and a value's precision was copied from the previous file.
    emitted_comp = sorted(set(computed) - REMOVED_MACROS)
    emitted_lit = sorted(set(LITERATURE_MACROS) - REMOVED_MACROS)
    clash = sorted(set(emitted_comp) & set(emitted_lit))
    if clash:
        print("ERROR: macro(s) both computed and sourced: " + ", ".join(clash))
        return 1
    # Every number a figure prints or draws must be emitted by this run.
    missing_fig = sorted(set(fig) - set(emitted_comp) - set(emitted_lit))
    if missing_fig:
        print("ERROR: FIGURE_MACROS name macro(s) that no generator emits:")
        for name in missing_fig:
            print(f"         \\{name}  ({', '.join(fig[name])})")
        return 1
    if args.list_unused:
        used = macros_in_use()
        unused = [n for n in emitted_lit + emitted_comp if n not in used]
        print(f"{len(unused)} macro(s) emitted but unused by paper.tex, tables/*.tex and "
              f"FIGURE_MACROS:")
        for n in unused:
            print(f"  \\{n}")
        return 0

    prev = previous_values()   # VALUES_DIFF.md only
    VALDIR.mkdir(parents=True, exist_ok=True)
    TABDIR.mkdir(parents=True, exist_ok=True)

    lit_lines, comp_lines, diff_rows = [], [], []
    BS = chr(92)
    for name in emitted_lit:
        val, src = LITERATURE_MACROS[name]
        lit_lines.append(BS + "newcommand{" + BS + name + "}{" + val + "}   % " + src)
        diff_rows.append((name, prev.get(name, "—"), val, "INPUT", compare(prev.get(name), val), src))
    for name in emitted_comp:
        c = computed[name]
        # The value is written as the generator formatted it. Each generator chooses its own
        # rounding (collect_computed.py or the script whose MACROS block it parses).
        gen = c["value"]
        comp_lines.append(BS + "newcommand{" + BS + name + "}{" + gen + "}   % " + c["source"]
                          + ("  [requires network]" if c["requires_network"] else ""))
        diff_rows.append((name, prev.get(name, "—"), gen, "COMPUTED", compare(prev.get(name), gen),
                          c["source"]))
    gone = sorted(set(prev) - set(emitted_comp) - set(emitted_lit))
    for name in gone:
        diff_rows.append((name, prev[name], "—", "—", "DROPPED (in the previous values.tex, "
                          "not emitted by this run)", ""))

    # ── assemble values_generated.tex ──
    # No generation timestamp is written here on purpose. A date would differ between two
    # runs of the same inputs, and byte-identical output across runs is the property that
    # makes the value chain checkable at all. The generation date of this file is
    # the date of the commit that carries it, which git already keeps and cannot be edited
    # by hand. Every macro instead carries the script and the inputs it came from.
    header = ["% GENERATED FILE — DO NOT EDIT. Written by 01_code/04_tables_values/make_tables_values.py",
              "% and copied to manuscript/values.tex by step 3/5 of run_all.sh. Every edit",
              "% made here is overwritten at the next run; change the generator instead. The trailing",
              "% comment on each macro is REPORTED, not authored: it is the 'source' string",
              "% that collect_computed.py attached to the value, and it describes where the",
              "% number came from, not what the macro means. This is not a source file.",
              "%",
              "% values_generated.tex — CANDIDATE values.tex written by make_tables_values.py.",
              "% DO NOT EDIT BY HAND: regenerate with run_all.sh (or make_tables_values.py).",
              "% Drop-in for \\input{values.tex}: every macro is defined.",
              "% Block 1 = sourced literature inputs; Block 2 = code-regenerated outputs.",
              "% There is no third block. Every macro here is either sourced or computed;",
              "% a macro that is neither fails the run by name rather than being copied",
              "% through from the previous run's output.",
              "% Generation date = the commit that carries this file; no timestamp is written",
              "% inline, so that two runs of the same inputs stay byte-identical.", ""]
    body = (["% ===== (1) Literature inputs (sourced constants, NOT computed) ====="] + sorted(lit_lines)
            + ["", "% ===== (2) Computed outputs (regenerated by the code) ====="] + sorted(comp_lines) + [""])
    (VALDIR / "values_generated.tex").write_text("\n".join(header + body), encoding="utf-8", newline="\n")

    # ── counts.json: the ONE place the macro counts are established ──
    # These numbers are quoted in three prose passages -- the data-availability section of
    # README.md, the network-failure message of run_all.sh, and section 4 of README.md --
    # and each used to carry its own copy. They disagreed, and the example is worth keeping
    # because the two numbers were both real: in 2026-09 the README said "36 of the 75
    # computed macros in values.tex require network", which were computed.json's totals and
    # not this file's -- values.tex carried 72 computed macros then, 35 of them network, the
    # 36th being a macro in REMOVED_MACROS that never reaches it. (Those figures are that
    # date's, not today's; today's are below, computed.) A count that describes this file has
    # to be taken FROM this file, at the moment it is written, which is here.
    # Every consumer reads counts.json; none of them counts anything itself.
    counts = {
        "literature": len(lit_lines),
        "computed": len(comp_lines),
        "computed_network": sum(1 for l in comp_lines if "[requires network]" in l),
        "total": len(lit_lines) + len(comp_lines),
        "computed_json_entries": len(computed),
        "note": "counts of manuscript/values.tex as written by make_tables_values.py. "
                "'computed_json_entries' is the larger number in computed.json, which "
                "includes macros listed in REMOVED_MACROS that are never emitted.",
    }
    (VALDIR / "counts.json").write_text(json.dumps(counts, indent=2) + "\n", encoding="utf-8", newline="\n")

    write_disagreements()
    write_eps_dyn(computed)

    # ── VALUES_DIFF.md ──
    n_lit = sum(1 for r in diff_rows if r[3] == "INPUT")
    n_comp = sum(1 for r in diff_rows if r[3] == "COMPUTED")
    n_match = sum(1 for r in diff_rows if r[3] == "COMPUTED" and r[4] == "MATCH")
    n_benign = sum(1 for r in diff_rows if r[3] == "COMPUTED" and r[4].startswith("diff:benign"))
    n_sub = sum(1 for r in diff_rows if r[3] == "COMPUTED" and "SUBSTANTIVE" in r[4])
    out = [
        "# VALUES_DIFF.md — generated values vs manuscript snapshot (Stage A, non-destructive)",
        "",
        f"Macros: **{n_lit} literature-input**, **{n_comp} computed**. There is no "
        "carried-over family: a macro with no generator and no sourced value fails the run.",
        f"Computed verdicts: {n_match} match, {n_benign} benign (MC noise/rounding), **{n_sub} substantive**.",
        "",
        "The manuscript is NOT modified. `diff:benign` = within MC noise / rounding; "
        "`diff:SUBSTANTIVE` = inspect before adopting (Stage B). `INPUT` rows should match by "
        "construction (literature value = paper value).",
        "",
        "| Macro | Paper | Generated | Family | Verdict | Source |",
        "|---|---|---|---|---|---|",
    ]
    for name, pv, gv, fam, verdict, src in diff_rows:
        out.append(f"| `\\{name}` | {pv} | {gv} | {fam} | {verdict} | {src} |")
    (VALDIR / "VALUES_DIFF.md").write_text("\n".join(out) + "\n", encoding="utf-8", newline="\n")

    print(f"values_generated.tex: {n_lit} input + {n_comp} computed.")
    print(f"VALUES_DIFF.md: {n_match} match, {n_benign} benign, {n_sub} SUBSTANTIVE.")
    print("Manuscript untouched (Stage A).")
    return 0


def write_disagreements():
    """Write disagreements.tex (tab:disagreements): three disagreements against two outputs.

    The cells are in words, except the location row, which reads \\xoverRangeFactor, and
    the class row, whose factor eps^(-1/2) is the exact ratio of the two power laws, capped
    for the AMOC at \\classFactorAtEpsDynAMOC, its value at eps_dyn. No
    number is typed here. The damage row says only that the price moves in proportion to
    the loss (eq:fold_scc), so it cites no estimate of the damage. The deadline column is
    eq:tc_bound, which contains neither the loss nor the exponent and is linear in the
    warming left before the threshold. The table is written here, next to its sources, so
    that a cell cannot drift from the macro it quotes.
    """
    lines = [
        "% GENERATED FILE — produced by make_tables_values.py (write_disagreements). Cells are",
        "% words, a macro of values.tex, or exact properties of the equations named in the docstring.",
        "\\begin{tabular}{@{}lll@{}}",
        "\\toprule",
        "Disagreement over & Tipping price & Deadline bound \\eqref{eq:tc_bound} \\\\",
        "\\midrule",
        "Damage at tipping & its level, in proportion & nothing \\\\",
        "Location of the threshold & $\\times\\xoverRangeFactor$ across the published range "
        "& in proportion to the warming left \\\\",
        # The factor stops at the lower edge of the regime (the appendix on where the elements sit).
        "Class (motion of the boundary) & $\\times\\eps^{-1/2}$, up to $\\classFactorAtEpsDynAMOC$ for the "
        "AMOC & nothing \\\\",
        "\\bottomrule",
        "\\end{tabular}",
        "",
    ]
    (TABDIR / "disagreements.tex").write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print("  regenerated 02_output/tables/disagreements.tex")


def write_eps_dyn(computed):
    """Write eps_dyn.tex (tab:eps_dyn, the appendix on where the elements sit): the lower edge of the fixed-budget
    regime and the factor F by which the leading law lifts the price between today's
    proximity and eps_dyn (the width of the window; the lift of the full price only if the
    state is inside the noise layer today), per element and recovery rate, on the
    three emission paths. The caption and the note are in paper.tex, around the \\input. Every number is a macro of values.tex (collect_computed.py). An F
    cell reads "---" where eps_dyn >= eps_now: the lower edge already lies above today's
    proximity and the geometry lifts nothing; that is decided here from computed.json, the
    same file the macros come from, so the dash and the macro cannot disagree."""
    rows = [  # (element, recovery rate cell, eps_now macro, case suffix)
        ("AMOC", "$\\thetaAMOChat$, record", "epsAMOCnat", "AMOC"),
        ("Amazon", "$\\kappaAmazonBoulton$, vegetation index", "epsAmazonnat", "AmazonBoulton"),
        ("Amazon", "one per century, assumed", "epsAmazonnat", "AmazonSlow"),
        ("West Antarctic ice sheet", "$1/\\relaxWAISHillLo$, flow", "epsWAISnat", "WAISfast"),
        ("West Antarctic ice sheet", "$1/\\relaxWAISHillHi$, flow", "epsWAISnat", "WAISslow"),
        ("West Antarctic ice sheet", "one per century, slower modes", "epsWAISnat", "WAIScentury"),
    ]
    lines = [
        "% GENERATED FILE — produced by make_tables_values.py (write_eps_dyn). Every number is a",
        "% macro of values.tex; an F cell is --- where eps_dyn >= eps_now (computed.json).",
        "\\begin{tabular}{@{}llccccccc@{}}",
        "\\toprule",
        " & & & \\multicolumn{2}{c}{Today's rate} & \\multicolumn{2}{c}{SSP2-4.5} "
        "& \\multicolumn{2}{c}{SSP3-7.0} \\\\",
        "\\cmidrule(lr){4-5}\\cmidrule(lr){6-7}\\cmidrule(l){8-9}",
        "Element & Recovery rate $\\theta$ (per year) & $\\eps_{\\mathrm{now}}$ "
        + "& $\\eps_{\\mathrm{dyn}}$ & $F$ " * 3 + "\\\\",
        "\\midrule",
    ]
    for el, theta, now, suf in rows:
        cells = [el, theta, "$\\" + now + "$"]
        for pkey in ("", "SSPmid", "SSPhigh"):
            e_name, a_name = f"epsDyn{suf}{pkey}", f"amp{suf}{pkey}"
            if e_name not in computed or a_name not in computed:
                raise SystemExit(f"[ERROR] write_eps_dyn: {e_name} or {a_name} missing "
                                 "from computed.json")
            enters = float(computed[e_name]["value"]) < float(computed[now]["value"])
            cells += ["$\\" + e_name + "$", ("$\\" + a_name + "$") if enters else "---"]
        lines.append(" & ".join(cells) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", ""]
    (TABDIR / "eps_dyn.tex").write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print("  regenerated 02_output/tables/eps_dyn.tex")


if __name__ == "__main__":
    # The exit code carries the verdict: step 3/5 of run_all.sh stops the run on a
    # non-zero code, and an unwired macro must stop it rather than reach the manuscript.
    sys.exit(main())
