# -*- coding: utf-8 -*-
"""
REPLICATION HEADER
  PRODUCES   nothing on disk; a module
  FEEDS      every literature-input macro of values.tex, and the sourced constants of computed.json
  INPUTS     none; each constant carries its citation inline
  SEED       none
  RUNTIME    under 1 s
  IMPLEMENTS no equation; the sourced constants of tab:inputs

inputs_literature.py — SOURCED literature / scenario constants used in the manuscript.

These are INPUTS, not outputs: each is a cited constant or a modelling choice, NOT a
quantity computed by the code. They are listed here, each with its source, so the value
generator (make_tables_values.py) can emit them into values.tex WITHOUT pretending they
were computed. Anti-fabrication rule: a macro classified "literature-input" that has no
identifiable source is listed in UNSOURCED below and never given an invented value. A
macro in that dict is not emitted, so the run fails on it by name in make_tables_values.py
rather than reaching the manuscript.

Two dicts:
  LITERATURE_MACROS  : macros that appear verbatim in values.tex (name -> (value_str, source))
  DERIVATION_INPUTS  : sourced constants that are NOT macros but feed computed outputs
                       (e.g. current warming, TCRE) — used by collect_computed.py.
"""

# --- macros emitted verbatim into values.tex (literature/scenario constants) ---
LITERATURE_MACROS = {
    # --- van2026three, Table 1, as generated by MakeTable1.m of their replication package.
    # These are THEIR calibration, read from the code rather than from the December 2023
    # working paper, whose single-threshold model they no longer describe.
    "bhpChiPre":  ("1.8",    "Hambel, van der Ploeg and van den Bremer, replication package, Zenodo 20075290 (2026-05-07), Code_Parameters.m / Code_Initiation.m, as printed by MakeTable1.m — chi_pre, TCRE pre-tip, degC/TtC"),
    "bhpChiPost": ("2.4",    "Hambel, van der Ploeg and van den Bremer, replication package, Zenodo 20075290 (2026-05-07), Code_Parameters.m / Code_Initiation.m, as printed by MakeTable1.m — chi_post, TCRE post-tip, degC/TtC"),
    "bhpStates":  ("6",      "Hambel, van der Ploeg and van den Bremer, replication package, Zenodo 20075290 (2026-05-07), Code_Parameters.m / Code_Initiation.m, as printed by MakeTable1.m — H, number of tipping states"),
    "bhpRungs":   ("5",      "Hambel, van der Ploeg and van den Bremer, replication package, Zenodo 20075290 (2026-05-07), Code_Parameters.m / Code_Initiation.m, as printed by MakeTable1.m — transitions between the H states"),
    "bhpTstar":   ("1",      "Hambel, van der Ploeg and van den Bremer, replication package, Zenodo 20075290 (2026-05-07), Code_Parameters.m / Code_Initiation.m, as printed by MakeTable1.m — T*, tipping threshold, degC"),
    "bhpTzero":   ("1.1",    "Hambel, van der Ploeg and van den Bremer, replication package, Zenodo 20075290 (2026-05-07), Code_Parameters.m / Code_Initiation.m, as printed by MakeTable1.m — T_0, initial temperature anomaly, degC"),
    # The unit travels with the number: the model's own h_1T is 0.0035 per degC per year
    # (bhp_h1T below), and a bare "0.35" read in those units is off by a factor of 100.
    # Math mode only (the manuscript writes $h_1^{T}=\bhpHone$).
    "bhpHone":    (r"0.35\%\,{}^{\circ}\mathrm{C}^{-1}\,\mathrm{yr}^{-1}","Hambel, van der Ploeg and van den Bremer, replication package, Zenodo 20075290 (2026-05-07), Code_Parameters.m / Code_Initiation.m, as printed by MakeTable1.m — h_1T, marginal arrival rate of the first tipping point, %/degC/yr"),
    "bhpEzero":   ("611.11", "Hambel, van der Ploeg and van den Bremer, replication package, Zenodo 20075290 (2026-05-07), Code_Parameters.m / Code_Initiation.m, as printed by MakeTable1.m — E_0, initial cumulative emissions, GtC"),
    "bhpFzero":   ("9.157",  "Hambel, van der Ploeg and van den Bremer, replication package, Zenodo 20075290 (2026-05-07), Code_Parameters.m / Code_Initiation.m, as printed by MakeTable1.m — F_0, initial emissions in BAU, GtC/yr"),
    "bhpTupper":  ("3",      "modelling choice — upper end of the warming range the tipping premium is quoted over, degC"),

    # Post-tipping realization timescale T (yr) — Armstrong McKay et al. 2022, Science, Table 1
    "TAMOC":   ("50",   "Armstrong McKay et al. 2022, Science — Table 1 central"),
    "TAmazon": ("100",  "Armstrong McKay et al. 2022, Science — Table 1 central"),
    "TWAIS":   ("2000", "Armstrong McKay et al. 2022, Science — Table 1 central"),
    # TSPG removed (T-D): unused in paper.tex AND paper_past.tex.
    # Central temperature threshold ΔT* (°C) — Armstrong McKay et al. 2022, Table 1
    "DTstarAMOC":   ("4",   "Armstrong McKay et al. 2022, Science — central threshold"),
    "DTstarAmazon": ("3.5", "Armstrong McKay et al. 2022, Science — central threshold"),
    "DTstarWAIS":   ("1.5", "Armstrong McKay et al. 2022, Science — central threshold"),
    "DTstarSPG":    ("1.8", "Armstrong McKay et al. 2022 (SPG; UNUSED in paper.tex)"),
    # Modelling choices / scenario knobs
    "rhoBase":       ("0.03", "modelling choice — baseline discount rate (Nordhaus–Stern midpoint)"),
    "sigmaPriorPct": (r"30\%", "modelling choice — +/- prior width on sigma"),
    "EglobalRate":   ("40",   "Global Carbon Project — gross global emissions ~40 GtCO2/yr"),
    # Upper end of the common damage sweep L/GDP ~ U[0, Lmax], anchored on the aggregate
    # tipping damage of Dietz et al. 2021. It was the last macro carried over with no
    # source attached, and the same 0.67 was additionally written out ten times across
    # calibration_ci.py, eps_inf_ci.py, fig_forest_tc.py (three element dicts each) and
    # reduced_form_scc.py, none of the copies aware of the others. All four now import
    # "Lmax" from here, so the value has exactly one home: change it here and the Monte
    # Carlo, the forest figure, the reduced form and values.tex all move together.
    "Lmax":          ("0.67", "Dietz et al. 2021, PNAS — upper end of the common damage sweep"),
    # sigmaWAISmed removed (T-D): unused in paper.tex AND paper_past.tex.
    # Backstop cost scenarios ($/tCO2) — Fuss et al. 2018, DACCS range
    "gammabarLow":   ("100", "Fuss et al. 2018 — DACCS mature low end"),
    "cbarMid":       ("300", "Fuss et al. 2018 — DACCS mid"),
    "gammabarHigh":  ("600", "Fuss et al. 2018 — DACCS near-term high end"),
    "cbarRangeLow":  ("100", "Fuss et al. 2018 — candidate-backstop range low"),
    "cbarRangeHigh": ("600", "Fuss et al. 2018 — candidate-backstop range high"),
    # Reported IAM SCC figures used for comparison (cited, NOT recomputed here)
    "sccDietzPct":       (r"25\%", "Dietz et al. 2021, PNAS — reported tipping uplift"),
    "sccDietzCentral":   ("25",   "Dietz et al. 2021, PNAS — reported central tipping SCC"),
    # --- tab:disagreements, damage row. Verified on the abstract (ideas.repec.org record of
    # Environmental and Resource Economics 68(1), 197-225): "a three- to four-fold increase
    # in the 2015 SCC relative to DICE ... When catastrophic impacts are also factored in,
    # the SCC increases by four- to five-fold." The range is the union, three to five.
    "dmgSCCRatioLo":     ("3",    "Howard and Sterner 2017, Environmental and Resource Economics 68(1):197-225, abstract — SCC relative to DICE-2013R with their preferred damage function, low end of three- to four-fold"),
    "dmgSCCRatioHi":     ("5",    "Howard and Sterner 2017, Environmental and Resource Economics 68(1):197-225, abstract — SCC relative to DICE-2013R with catastrophic impacts, high end of four- to five-fold"),
    "sccDietzBaseline":  ("52","Dietz et al. 2021, PNAS — reported baseline SCC"),
    "sccDietzTotalLow":  ("13",   "Dietz et al. 2021, PNAS — reported low"),
    "sccDietzTotalHigh": ("69",   "Dietz et al. 2021, PNAS — reported high"),
    "sccDietzScenLow":   ("24",   "Dietz et al. 2021 (UNUSED in paper.tex)"),
    "sccDietzScenHigh":  ("118",  "Dietz et al. 2021 (UNUSED in paper.tex)"),
    "sccCaiLow":         ("15",   "Cai & Lontzek 2019, JPE (UNUSED in paper.tex)"),
    "sccCaiHigh":        ("80",   "Cai & Lontzek 2019, JPE (UNUSED in paper.tex)"),
    # The Amazon's premium on the SCC in Dietz et al. (2021), quoted in the
    # introduction. \sccDietzBaseline above is the same baseline rounded to 52 and retired
    # (REMOVED_MACROS); these carry the two decimals of the table.
    "dietzSCCbase":      ("52.03", "Dietz, Rising, Stoerk and Wagner (2021), PNAS 118(34), e2103081118; value read and checked by the author; Table 2, expected SCC with no tipping point ('None'), 2020 US$/tCO2"),
    "dietzAmazonSCCadd": ("0.04",  "Dietz, Rising, Stoerk and Wagner (2021), PNAS 118(34), e2103081118; value read and checked by the author; Table 2, expected SCC with Amazon dieback (52.07) minus 'None' (52.03), 2020 US$/tCO2; the table prints the two levels, not the difference"),
    # The relaxation time of the West Antarctic ice sheet's flow, the recovery rate
    # the lower edge of the fixed-budget regime is read at (the appendix on where the elements sit, tab:eps_dyn).
    # Hill et al. (2023), The Cryosphere 17, 3739-3759, doi:10.5194/tc-17-3739-2023, Section
    # 4.1 (publisher PDF): "The calculated e-folding flux response time
    # reveals that the Antarctic-wide recovery time is in good agreement for all models,
    # ranging between 10 and 20 years"; Amundsen Sea basins: "e-folding times < 20 years".
    "relaxWAISHillLo":   ("10",   "Hill et al. 2023, The Cryosphere 17:3739-3759, doi:10.5194/tc-17-3739-2023 — e-folding relaxation time of the grounding-line flux after a 20-yr ocean perturbation, Antarctic-wide, low end of 'between 10 and 20 years' (yr)"),
    "relaxWAISHillHi":   ("20",   "Hill et al. 2023, The Cryosphere 17:3739-3759, doi:10.5194/tc-17-3739-2023 — e-folding relaxation time of the grounding-line flux after a 20-yr ocean perturbation, Antarctic-wide, high end of 'between 10 and 20 years' (yr)"),
    "dietzAmazonSCCpct": ("0.1",   "Dietz, Rising, Stoerk and Wagner (2021), PNAS 118(34), e2103081118; value read and checked by the author; Table 2, 'Increase due to TP, %', Amazon; text: 'Dieback of the Amazon rainforest leads to a modest 0.1% increase in the expected SCC'"),
}

# --- sourced constants that FEED computed outputs (not macros themselves) ---
DERIVATION_INPUTS = {
    # --- van2026three calibration, feeding bhp_bound.py. Same source as the bhp* macros.
    "bhp_h1T":     (0.0035,  "Hambel, van der Ploeg and van den Bremer, replication package, Zenodo 20075290 (2026-05-07), Code_Parameters.m / Code_Initiation.m, as printed by MakeTable1.m — calib.lambda12, /degC/yr"),
    "bhp_Tstar":   (1.0,     "Hambel, van der Ploeg and van den Bremer, replication package, Zenodo 20075290 (2026-05-07), Code_Parameters.m / Code_Initiation.m, as printed by MakeTable1.m — calib.Tmin, degC"),
    "bhp_T0":      (1.1,     "Hambel, van der Ploeg and van den Bremer, replication package, Zenodo 20075290 (2026-05-07), Code_Parameters.m / Code_Initiation.m, as printed by MakeTable1.m — calib.T0, degC"),
    "bhp_rho":     (0.0508,  "Hambel, van der Ploeg and van den Bremer, replication package, Zenodo 20075290 (2026-05-07), Code_Parameters.m / Code_Initiation.m, as printed by MakeTable1.m — calib.rho, /yr"),
    "bhp_lambda2": (0.08,    "Hambel, van der Ploeg and van den Bremer, replication package, Zenodo 20075290 (2026-05-07), Code_Parameters.m / Code_Initiation.m, as printed by MakeTable1.m — calib.lambdaij, /yr"),
    "bhp_chi_pre": (0.0018,  "Hambel, van der Ploeg and van den Bremer, replication package, Zenodo 20075290 (2026-05-07), Code_Parameters.m / Code_Initiation.m, as printed by MakeTable1.m — calib.chi_pre, degC/GtC"),
    "bhp_E0":      (611.11,  "Hambel, van der Ploeg and van den Bremer, replication package, Zenodo 20075290 (2026-05-07), Code_Parameters.m / Code_Initiation.m, as printed by MakeTable1.m — calib.E0, GtC"),
    "bhp_F0":      (9.157,   "Hambel, van der Ploeg and van den Bremer, replication package, Zenodo 20075290 (2026-05-07), Code_Parameters.m / Code_Initiation.m, as printed by MakeTable1.m — F_0 = (1-alpha) Y_0 / b, GtC/yr"),
    "bhp_rungs":   (5.0,     "Hambel, van der Ploeg and van den Bremer, replication package, Zenodo 20075290 (2026-05-07), Code_Parameters.m / Code_Initiation.m, as printed by MakeTable1.m — calib.tipping_states"),
    "bhp_nu":      (1.0,     "their mechanism: the loss is D_1 (chi_post - chi_pre) E, strictly linear in cumulative emissions, so nu = 1 exactly"),
    "bhp_T_upper": (3.0,     "modelling choice — upper end of the quoted warming range, degC"),

    # --- Recovery rates for the lower edge of the fixed-budget regime (eps_dyn).
    # Boulton, Lenton and Boers (2022), Nature Climate Change 12, 271-278,
    # doi:10.1038/s41558-022-01287-8, Methods (p. 9): "Inverting kappa gives the
    # characteristic time scale of the system; for the VOD, we find 1/kappa = 1.240 months".
    # It is the time scale of the VEGETATION INDEX (VOD), regional mean, not a measured
    # recovery time of the forest; the paper says so wherever it uses it.
    "recovery_months_Amazon_Boulton": (1.240, "Boulton, Lenton and Boers 2022, Nature Climate Change 12:271-278, Methods p. 9 — 1/kappa of the VOD vegetation index, regional mean AR(1), months"),
    # Not a measurement: the sensitivity reading in which the element recovers over a
    # century. Applied to the Amazon (forest recovery, unmeasured) and to the slower modes
    # of the ice sheet (Robel, Roe and Haseloff 2018, JGR Earth Surface 123:2205-2227,
    # abstract: "a fast time scale of decades to centuries, and a slow time scale of millennia").
    "recovery_time_century": (100.0, "sensitivity assumption, not a measurement: a recovery time of one century (yr)"),

    # --- The md5 of the AMOC series as PIK served it on 2026-10-01
    # (00_data/amoc/PROVENANCE.md). ews_calibration.py refuses any other file, and
    # fetch_pik_sg_index.py checks the download against it. Not a macro.
    "amoc_series_md5": ("c48516162322edebaaf113b2841f93be", "md5 of sg_index_hadisst.txt, Caesar et al. 2018 via PIK, downloaded 2026-10-01 (00_data/amoc/PROVENANCE.md)"),

    # The source the text cites (forster2024indicators), not AR6, which gives 1.09 (2011-2020).
    "DT_current":   (1.2,  "Forster et al. 2024, Indicators of Global Climate Change 2023, ESSD 16:2625-2658 — observed warming above pre-industrial, 2014-2023 average, 1.19 [1.06 to 1.30] (°C)"),
    "TCRE":         (0.45, "IPCC AR6 WG1 2021 — °C per 1000 GtCO2 (central)"),
    # --- The Monte-Carlo settings of the calibration-inputs appendix, written out until now in
    # calibration_ci.py, eps_inf_ci.py (twice) and fig_forest_tc.py, each on its own. They
    # have one home here; the scripts import them, and the text quotes them as macros.
    # The AR6 likely range, read as the 17th and 83rd centiles of the
    # normal law the Monte Carlo draws from. TCRE_sd is COMPUTED from the two ends below (after
    # this dict), never typed; the only constraint on the draw is TCRE > 0, imposed by
    # rejection in tcre_draw.py.
    "TCRE_likely_lo": (0.27, "IPCC AR6 WG1 2021, SPM D.1.1, likely range — lower end, °C per 1000 GtCO2"),
    "TCRE_likely_hi": (0.63, "IPCC AR6 WG1 2021, SPM D.1.1, likely range — upper end, °C per 1000 GtCO2"),
    # Realization timescales H: ends of the ranges of Armstrong McKay et al. 2022, Table 1, read
    # by calibration_ci.py (the centrals are TAMOC, TAmazon, TWAIS above). In earlier versions
    # they were typed in calibration_ci.py's element dicts and again in Table 5.
    "T_AMOC_p5":    (15.0,    "Armstrong McKay et al. 2022, Science — Table 1, AMOC collapse, timescale, low end of range (yr)"),
    "T_AMOC_p95":   (300.0,   "Armstrong McKay et al. 2022, Science — Table 1, AMOC collapse, timescale, high end of range (yr)"),
    "T_Amazon_p5":  (50.0,    "Armstrong McKay et al. 2022, Science — Table 1, Amazon dieback, timescale, low end of range (yr)"),
    "T_Amazon_p95": (200.0,   "Armstrong McKay et al. 2022, Science — Table 1, Amazon dieback, timescale, high end of range (yr)"),
    "T_WAIS_p5":    (500.0,   "Armstrong McKay et al. 2022, Science — Table 1, West Antarctic ice sheet, timescale, low end of range (yr)"),
    "T_WAIS_p95":   (13000.0, "Armstrong McKay et al. 2022, Science — Table 1, West Antarctic ice sheet, timescale, high end of range (yr)"),
    "N_MC":         (100000, "Monte Carlo draws in calibration_ci.py, eps_inf_ci.py and fig_forest_tc.py (modelling choice)"),
    "sigma_prior_lo": (0.05, "lower end of the common log-uniform noise prior of the Amazon and the ice sheet (modelling choice, common to the two elements)"),
    "sigma_prior_hi": (0.45, "upper end of the common log-uniform noise prior of the Amazon and the ice sheet (modelling choice, common to the two elements)"),

    # --- Temperature thresholds DT* of the three fold-class elements, central value and
    # the ends of the reported range (°C above pre-industrial). Armstrong McKay et al.
    # 2022, Table 1.
    #
    # These nine numbers were written out THREE times before 2026-09-22 -- in the element
    # dicts of calibration_ci.py, eps_inf_ci.py and fig_forest_tc.py, none of the three
    # aware of the others -- and a fourth time as bare literals in the DT* column of
    # tab:inputs in paper.tex. That is the configuration a value drifts in. They have one
    # home here now, and the three scripts read them; tab:inputs quotes them as macros.
    #
    # The centrals are ALSO emitted as macros, from LITERATURE_MACROS above, where they are
    # strings rather than floats. The two are checked against each other at the bottom of
    # this module rather than trusted to stay equal.
    "DTstar_AMOC_best":   (4.0, "Armstrong McKay et al. 2022, Science — Table 1, AMOC collapse, central threshold (°C)"),
    "DTstar_AMOC_p5":     (1.4, "Armstrong McKay et al. 2022, Science — Table 1, AMOC collapse, low end of the reported threshold range (°C)"),
    "DTstar_AMOC_p95":    (8.0, "Armstrong McKay et al. 2022, Science — Table 1, AMOC collapse, high end of the reported threshold range (°C)"),
    "DTstar_Amazon_best": (3.5, "Armstrong McKay et al. 2022, Science — Table 1, Amazon dieback, central threshold (°C)"),
    "DTstar_Amazon_p5":   (2.0, "Armstrong McKay et al. 2022, Science — Table 1, Amazon dieback, low end of the reported threshold range (°C)"),
    "DTstar_Amazon_p95":  (6.0, "Armstrong McKay et al. 2022, Science — Table 1, Amazon dieback, high end of the reported threshold range (°C)"),
    "DTstar_WAIS_best":   (1.5, "Armstrong McKay et al. 2022, Science — Table 1, West Antarctic ice sheet, central threshold (°C)"),
    "DTstar_WAIS_p5":     (1.0, "Armstrong McKay et al. 2022, Science — Table 1, West Antarctic ice sheet, low end of the reported threshold range (°C)"),
    "DTstar_WAIS_p95":    (3.0, "Armstrong McKay et al. 2022, Science — Table 1, West Antarctic ice sheet, high end of the reported threshold range (°C)"),
    # sigmaAmazon removed: 0.15 could not be traced (neither sqrt(2*lambda*Var), nor the sweep
    # [0.05,0.45] actually used, nor wired into any computation). Amazon prior = log-uniform
    # sweep labelled "effective VOD noise"; see calibration_ci.py and eps_inf_ci.py.
    "sigma_cv_AMOC": (0.30, "prior CV on AMOC sigma (= sigmaPriorPct), for P10/P90"),
    # The MEDIAN of the AMOC sigma prior drawn by the three Monte-Carlo scripts
    # (calibration_ci, eps_inf_ci, fig_forest_tc). It is \sigmaAMOChat, the output of
    # ews_calibration.py, but those scripts run before the network step and must stay
    # self-contained: none of their macros depends on sigma, and reading the capture would
    # mark all of them [requires network]. So it is declared once here, and
    # collect_computed.py -- the one place that sees both -- FAILS if it drifts from the
    # capture by more than 5e-4. It was 0.258, written out three times, in earlier versions
    # replaced -ln AC1 by the annual-mean inversion (lambda 0.4933 -> 0.7928).
    "sigma_mu_AMOC": (0.3725, "median of the AMOC sigma prior in the Monte-Carlo scripts = "
                              "sigma_clim (full sample) of ews_calibration.py, K yr^-1/2; "
                              "checked against the capture by collect_computed.py"),
}

# The standard deviation of the TCRE draw: the normal law whose 17th and 83rd centiles are the
# AR6 likely range, (hi - lo) / 2 / z(0.83). Computed, never typed.
from statistics import NormalDist as _NormalDist  # noqa: E402
DERIVATION_INPUTS["TCRE_sd"] = (
    (DERIVATION_INPUTS["TCRE_likely_hi"][0] - DERIVATION_INPUTS["TCRE_likely_lo"][0])
    / 2.0 / _NormalDist().inv_cdf(0.83),
    "computed: (TCRE_likely_hi - TCRE_likely_lo) / 2 / z(0.83), the AR6 likely range "
    "(SPM D.1.1) as the 17th-83rd centiles of a normal law, °C per 1000 GtCO2")
del _NormalDist

# Macros explicitly WITHOUT an identified source go here, name -> what is missing.
# None at present: every literature-input macro above carries its source.
#
# The dict is kept although it is empty, because it is now the ONLY place an unsourced
# value can be recorded. Until 2026-09 there was a second: make_tables_values.py would
# copy a macro it could not account for straight out of the manuscript under a marker,
# which meant an unsourced number could sit in values.tex indefinitely without ever being
# written down as unsourced. That path is gone. A value that belongs in neither this file
# nor computed.json now stops the run.
UNSOURCED = {}


# --- the one constant that lives in BOTH dicts, checked rather than trusted ---------
# The central threshold of each element is a macro (a string, typeset in tab:inputs) and a
# derivation input (a float, drawn from). Two representations of one number is exactly the
# configuration that lets a value change in one place and not the other, and the check
# costs nothing, so it runs at import, for every script that imports this module.
for _el in ("AMOC", "Amazon", "WAIS"):
    _macro, _deriv = "DTstar" + _el, "DTstar_" + _el + "_best"
    if _macro not in LITERATURE_MACROS or _deriv not in DERIVATION_INPUTS:
        raise SystemExit("[ERROR] inputs_literature.py: %s and %s must both exist; the "
                         "central threshold of %s is quoted in tab:inputs and drawn from "
                         "in the Monte Carlo." % (_macro, _deriv, _el))
    if float(LITERATURE_MACROS[_macro][0]) != float(DERIVATION_INPUTS[_deriv][0]):
        raise SystemExit("[ERROR] inputs_literature.py: %s = %s but %s = %s. The macro the "
                         "table prints and the value the Monte Carlo draws around are the "
                         "same threshold; make them agree here."
                         % (_macro, LITERATURE_MACROS[_macro][0],
                            _deriv, DERIVATION_INPUTS[_deriv][0]))
    if not (float(DERIVATION_INPUTS["DTstar_" + _el + "_p5"][0])
            < float(DERIVATION_INPUTS[_deriv][0])
            < float(DERIVATION_INPUTS["DTstar_" + _el + "_p95"][0])):
        raise SystemExit("[ERROR] inputs_literature.py: the %s threshold range does not "
                         "bracket its central value." % _el)
del _el, _macro, _deriv


# --- the range ends, as macros, DERIVED from the floats above rather than retyped ------
# The DT* column of tab:inputs printed "[1.4,8.0]", "[2.0,6.0]" and "[1.0,3.0]" as bare
# literals in paper.tex, which is the one thing the manuscript is not allowed to contain
# and, worse here, a sixth and seventh copy of numbers the crossover macros now also read.
# They are emitted as macros instead, and they are not typed a second time: the strings
# below are formatted FROM the sourced floats, so the table and the Monte Carlo cannot
# print different ends of the same interval.
#
# One decimal, because that is the precision Armstrong McKay et al. report and the
# precision the column was set in.
for _el in ("AMOC", "Amazon", "WAIS"):
    for _suffix, _key in (("Lo", "p5"), ("Hi", "p95")):
        _name = "DTstar" + _el + _suffix
        _val, _src = DERIVATION_INPUTS["DTstar_%s_%s" % (_el, _key)]
        LITERATURE_MACROS[_name] = ("%.1f" % float(_val), _src)
del _el, _suffix, _key, _name, _val, _src

# --- Macros for the Monte-Carlo settings of the calibration-inputs appendix and Table 5, built from
# the constants above (the ones the scripts import), never typed a second time.
_D = DERIVATION_INPUTS
LITERATURE_MACROS["TCREmean"] = ("%g" % _D["TCRE"][0], _D["TCRE"][1])
LITERATURE_MACROS["TCRElikelyLo"] = ("%g" % _D["TCRE_likely_lo"][0], _D["TCRE_likely_lo"][1])
LITERATURE_MACROS["TCRElikelyHi"] = ("%g" % _D["TCRE_likely_hi"][0], _D["TCRE_likely_hi"][1])
# two significant figures
LITERATURE_MACROS["TCREsd"] = ("%.2g" % _D["TCRE_sd"][0], _D["TCRE_sd"][1] + " (%.5f)" % _D["TCRE_sd"][0])
LITERATURE_MACROS["NMonteCarlo"] = ("{:,}".format(int(_D["N_MC"][0])).replace(",", "{,}"), _D["N_MC"][1])
LITERATURE_MACROS["sigmaPriorLo"] = ("%g" % _D["sigma_prior_lo"][0], _D["sigma_prior_lo"][1])
LITERATURE_MACROS["sigmaPriorHi"] = ("%g" % _D["sigma_prior_hi"][0], _D["sigma_prior_hi"][1])
# Table 5 reports the median and P10-P90 of that prior (not of the AMOC estimate): closed form
# for a log-uniform on [lo, hi], quantile q at lo (hi/lo)^q.
_slo, _shi = _D["sigma_prior_lo"][0], _D["sigma_prior_hi"][0]
for _name, _q in (("sigmaPriorMed", 0.5), ("sigmaPriorPten", 0.1), ("sigmaPriorPninety", 0.9)):
    LITERATURE_MACROS[_name] = ("%.2f" % (_slo * (_shi / _slo) ** _q),
                                "closed form: quantile %g of the log-uniform prior on [%g, %g]" % (_q, _slo, _shi))
del _D, _slo, _shi, _name, _q
# Table 5, timescale ranges: TAMOCLo/Hi etc., thousands written {,} by the generator.
for _el in ("AMOC", "Amazon", "WAIS"):
    for _suffix, _key in (("Lo", "p5"), ("Hi", "p95")):
        _v, _src = DERIVATION_INPUTS["T_%s_%s" % (_el, _key)]
        LITERATURE_MACROS["T" + _el + _suffix] = ("{:,}".format(int(_v)).replace(",", "{,}"), _src)
del _el, _suffix, _key, _v, _src
